# Generated by Django 5.1.7 on 2025-10-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
