# Generated by Django 5.2.6 on 2025-10-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_department_alter_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Profile banner/cover image', null=True, upload_to='employee_documents/banners/'),
        ),
    ]
