# Generated by Django 5.2.6 on 2025-10-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_documents_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
