# Generated by Django 5.2.6 on 2025-11-12 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_client_delete_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this sprint belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sprint', models.ForeignKey(help_text='Sprint this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sprint.sprint')),
                ('user', models.ForeignKey(help_text='User who made the comment', on_delete=django.db.models.deletion.CASCADE, related_name='sprint_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sprint Comment',
                'verbose_name_plural': 'Sprint Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintRetrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(help_text='Sprint summary, feedback, and retrospective notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sprint', models.OneToOneField(help_text='Sprint this retrospective belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='sprint.sprint')),
            ],
            options={
                'verbose_name': 'Sprint Retrospective',
                'verbose_name_plural': 'Sprint Retrospectives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_tasks', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(help_text='Sprint this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sprint.sprint')),
            ],
            options={
                'verbose_name': 'Sprint Task',
                'verbose_name_plural': 'Sprint Tasks',
                'ordering': ['created_at'],
            },
        ),
    ]
