# Generated by Django 5.2.6 on 2025-10-31 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_userprofile'),
        ('finance', '0001_initial'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/description of the expense', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=15)),
                ('date', models.DateField(help_text='Date when expense occurred')),
                ('purchased_from', models.CharField(help_text='Vendor or source where purchase was made', max_length=255)),
                ('payment_mode', models.CharField(choices=[('upi', 'UPI'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('others', 'Others')], default='cash', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='Payment transaction ID or reference number', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Bank account from which expense was paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='setting.bankaccount')),
                ('purchased_by', models.ForeignKey(blank=True, help_text='Employee who made the purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
