# Generated by Django 5.2.6 on 2025-11-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='proposal_id',
            field=models.IntegerField(blank=True, help_text='ID of the proposal this contract is based on', null=True),
        ),
    ]
