# Generated by Django 5.2.6 on 2025-10-31 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0002_alter_project_client_delete_client'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number (e.g., INV-001)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('due_date', models.DateField(help_text='Due date for payment')),
                ('address', models.TextField(blank=True, help_text='Billing address', null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'Online'), ('bank_transaction', 'Bank Transaction'), ('other', 'Other')], help_text='Payment method', max_length=50, null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('invoice_file', models.FileField(blank=True, help_text='Invoice file/document', null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Bank account for payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='setting.bankaccount')),
                ('client', models.ForeignKey(blank=True, help_text='Client this invoice is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.client')),
                ('project', models.ForeignKey(blank=True, help_text='Project this invoice belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='projects.project')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
