# Generated by Django 5.2.6 on 2025-10-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Unique invoice number (e.g., INV-001). Auto-generated if not provided.', max_length=50, null=True, unique=True),
        ),
    ]
