# Generated by Django 5.2.6 on 2025-10-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_alter_employee_department_alter_employee_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name', max_length=255, unique=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes about the team', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the team is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Team members', related_name='team_memberships', to='employee.employee')),
                ('team_lead', models.ForeignKey(blank=True, help_text='Team lead/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-created_at'],
            },
        ),
    ]
