# Generated by Django 5.2.6 on 2025-10-31 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0006_userprofile'),
        ('projects', '0002_alter_project_client_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('highest', 'Highest'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('lowest', 'Lowest')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('testing', 'Testing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Employee assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='employee.employee')),
                ('project', models.ForeignKey(help_text='Project this task belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
